@startuml

title __ADAPTER's Class Diagram__\n

  namespace com.mad.p03.np2020.routine {
    namespace Adapter {
      class com.mad.p03.np2020.routine.Adapter.FocusAdapter {
          - TAG : String
          - context : Context
          - focusList : List<Focus>
          + FocusAdapter()
          + deleteDataFirebase()
          + getItemCount()
          + getItems()
          + notifiyItemChange()
          + onBindViewHolder()
          + onCreateViewHolder()
          + remove()
          + serializeToJson()
          - eventListener()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace Adapter {
      class com.mad.p03.np2020.routine.Adapter.HabitAdapter {
          {static} ~ TAG : String
          - UID : String
          - c : Context
          {static} - view : View
          + HabitAdapter()
          + getItemCount()
          + habit_serializeToJson()
          + onBindViewHolder()
          + onCreateViewHolder()
          + setOnItemClickListener()
          + writeHabit_Firebase()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace Adapter {
      class com.mad.p03.np2020.routine.Adapter.HabitGroupAdapter {
          + _habitGroupList : ArrayList<HabitGroup>
          - c : Context
          {static} - view : View
          + HabitGroupAdapter()
          + getItemCount()
          + onBindViewHolder()
          + onCreateViewHolder()
          + setOnItemClickListener()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace Adapter {
      interface com.mad.p03.np2020.routine.Adapter.HomeItemTouchHelperAdapter {
          {abstract} + onItemMove()
          {abstract} + onItemSwiped()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace Adapter {
      class com.mad.p03.np2020.routine.Adapter.HomePageAdapter {
          - TAG : String
          - mContext : Context
          - mItemTouchHelper : ItemTouchHelper
          - mOwner : LifecycleOwner
          - mSectionList : List<Section>
          + HomePageAdapter()
          + addItem()
          + getItemCount()
          + getSection()
          + onBindViewHolder()
          + onCreateViewHolder()
          + onItemMove()
          + onItemSwiped()
          + onSectionClick()
          + removeItem()
          + setTouchHelper()
          - confirmDelete()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace Adapter {
      class com.mad.p03.np2020.routine.Adapter.MyHomeItemTouchHelper {
          + MyHomeItemTouchHelper()
          + clearView()
          + getMovementFlags()
          + isItemViewSwipeEnabled()
          + isLongPressDragEnabled()
          + onMove()
          + onSelectedChanged()
          + onSwiped()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace Adapter {
      class com.mad.p03.np2020.routine.Adapter.MySpinnerColorAdapter {
          - mColors : Integer[]
          + MySpinnerColorAdapter()
          + getCount()
          + getItem()
          + getItemId()
          + getView()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace Adapter {
      class com.mad.p03.np2020.routine.Adapter.MySpinnerIconsAdapter {
          - mIcons : Integer[]
          + MySpinnerIconsAdapter()
          + getCount()
          + getItem()
          + getItemId()
          + getView()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace Adapter {
      class com.mad.p03.np2020.routine.Adapter.MyTaskTouchHelper {
          + MyTaskTouchHelper()
          + clearView()
          + getMovementFlags()
          + isItemViewSwipeEnabled()
          + isLongPressDragEnabled()
          + onMove()
          + onSelectedChanged()
          + onSwiped()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace Adapter {
      interface com.mad.p03.np2020.routine.Adapter.OnItemClickListener {
          {abstract} + onItemClick()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace Adapter {
      interface com.mad.p03.np2020.routine.Adapter.OnSectionListener {
          {abstract} + onSectionClick()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace Adapter {
      class com.mad.p03.np2020.routine.Adapter.TaskAdapter {
          - TAG : String
          - mContext : Context
          - mItemTouchHelper : ItemTouchHelper
          - mOwner : LifecycleOwner
          - mTaskList : List<Task>
          + TaskAdapter()
          + addItem()
          + getItemCount()
          + onBindViewHolder()
          + onCreateViewHolder()
          + onItemClicked()
          + onItemMove()
          + onItemSwiped()
          + removeTask()
          + setMyTaskTouchHelper()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace Adapter {
      interface com.mad.p03.np2020.routine.Adapter.TaskTouchHelperAdapter {
          {abstract} + onItemClicked()
          {abstract} + onItemMove()
          {abstract} + onItemSwiped()
      }
    }
  }
  

  com.mad.p03.np2020.routine.Adapter.FocusAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.mad.p03.np2020.routine.Adapter.FocusAdapter o-- com.mad.p03.np2020.routine.database.FocusDBHelper : focusDBHelper
  com.mad.p03.np2020.routine.Adapter.FocusAdapter o-- com.mad.p03.np2020.routine.Class.User : user
  com.mad.p03.np2020.routine.Adapter.HabitAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.mad.p03.np2020.routine.Adapter.HabitAdapter o-- com.mad.p03.np2020.routine.Class.Habit.HabitList : _habitList
  com.mad.p03.np2020.routine.Adapter.HabitAdapter o-- com.mad.p03.np2020.routine.database.HabitDBHelper : dbHandler
  com.mad.p03.np2020.routine.Adapter.HabitAdapter o-- com.mad.p03.np2020.routine.Adapter.OnItemClickListener : mListener
  com.mad.p03.np2020.routine.Adapter.HabitGroupAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.mad.p03.np2020.routine.Adapter.HabitGroupAdapter o-- com.mad.p03.np2020.routine.Adapter.OnItemClickListener : mListener
  com.mad.p03.np2020.routine.Adapter.HomePageAdapter .up.|> com.mad.p03.np2020.routine.Adapter.HomeItemTouchHelperAdapter
  com.mad.p03.np2020.routine.Adapter.HomePageAdapter .up.|> com.mad.p03.np2020.routine.Adapter.OnSectionListener
  com.mad.p03.np2020.routine.Adapter.HomePageAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.mad.p03.np2020.routine.Adapter.MyHomeItemTouchHelper -up-|> androidx.recyclerview.widget.ItemTouchHelper.Callback
  com.mad.p03.np2020.routine.Adapter.MyHomeItemTouchHelper o-- com.mad.p03.np2020.routine.Adapter.HomeItemTouchHelperAdapter : mAdapter
  com.mad.p03.np2020.routine.Adapter.MySpinnerColorAdapter -up-|> android.widget.BaseAdapter
  com.mad.p03.np2020.routine.Adapter.MySpinnerIconsAdapter -up-|> android.widget.BaseAdapter
  com.mad.p03.np2020.routine.Adapter.MyTaskTouchHelper -up-|> androidx.recyclerview.widget.ItemTouchHelper.Callback
  com.mad.p03.np2020.routine.Adapter.MyTaskTouchHelper o-- com.mad.p03.np2020.routine.Adapter.TaskTouchHelperAdapter : mTaskTouchHelperAdapter
  com.mad.p03.np2020.routine.Adapter.TaskAdapter .up.|> com.mad.p03.np2020.routine.Adapter.TaskTouchHelperAdapter
  com.mad.p03.np2020.routine.Adapter.TaskAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
