@startuml

title __DATABASE's Class Diagram__\n

  namespace com.mad.p03.np2020.routine {
    namespace database {
      class com.mad.p03.np2020.routine.database.CardDBHelper {
          {static} + COL1 : String
          {static} + COL2 : String
          {static} + DATABASE_NAME : String
          {static} + DATABASE_VERSION : int
          {static} + TABLE_NAME : String
          {static} - TAG : String
          + CardDBHelper()
          + onCreate()
          + onUpgrade()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace database {
      class com.mad.p03.np2020.routine.database.DBHelper {
          {static} ~ DATABASE_NAME : String
          {static} ~ DATABASE_VERSION : int
          {static} ~ mMyDatabaseListener : MyDatabaseListener
          + DBHelper()
          + onCreate()
          + onDowngrade()
          + onUpgrade()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace database {
      class com.mad.p03.np2020.routine.database.FocusDBHelper {
          + FocusDBHelper()
          + addData()
          + deleteAll()
          + describeContents()
          + getAllData()
          + isTableExists()
          + onCreate()
          + onDowngrade()
          + onUpgrade()
          + removeOneData()
          + writeToParcel()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace database {
      class com.mad.p03.np2020.routine.database.HabitDBHelper {
          - TAG : String
          + HabitDBHelper()
          + deleteHabit()
          + getAllHabits()
          + insertHabit()
          + onCreate()
          + onDowngrade()
          + onUpgrade()
          + updateCount()
          + updateHabit()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace database {
      class com.mad.p03.np2020.routine.database.HabitGroupDBHelper {
          - TAG : String
          + HabitGroupDBHelper()
          + getAllGroups()
          + insertGroup()
          + onCreate()
          + onDowngrade()
          + onUpgrade()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace database {
      interface com.mad.p03.np2020.routine.Interface.MyDatabaseListener {
          {abstract} + onDataAdd()
          {abstract} + onDataDelete()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace database {
      class com.mad.p03.np2020.routine.database.SectionDBHelper {
          - TAG : String
          {static} - mMyDatabaseListener : MyDatabaseListener
          + SectionDBHelper()
          + delete()
          + getAllSections()
          + getSection()
          + hasID()
          + insertSection()
          + onCreate()
          + onDowngrade()
          + onUpgrade()
          {static} + setMyDatabaseListener()
          + updatePosition()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace database {
      class com.mad.p03.np2020.routine.database.TaskDBHelper {
          - TAG : String
          {static} - mMyDatabaseListener : MyDatabaseListener
          + TaskDBHelper()
          + delete()
          + getAllTask()
          + hasID()
          + insertTask()
          + onCreate()
          + onDowngrade()
          + onUpgrade()
          {static} + setMyDatabaseListener()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace database {
      class com.mad.p03.np2020.routine.database.UserDBHelper {
          - TAG : String
          + UserDBHelper()
          + getUser()
          + insertUser()
          + onCreate()
          + onDowngrade()
          + onUpgrade()
      }
    }
  }
  

  com.mad.p03.np2020.routine.database.CardDBHelper -up-|> android.database.sqlite.SQLiteOpenHelper
  com.mad.p03.np2020.routine.database.DBHelper -up-|> android.database.sqlite.SQLiteOpenHelper
  com.mad.p03.np2020.routine.database.FocusDBHelper .up.|> android.os.Parcelable
  com.mad.p03.np2020.routine.database.FocusDBHelper -up-|> com.mad.p03.np2020.routine.database.DBHelper
  com.mad.p03.np2020.routine.database.HabitDBHelper -up-|> com.mad.p03.np2020.routine.database.DBHelper
  com.mad.p03.np2020.routine.database.HabitGroupDBHelper -up-|> com.mad.p03.np2020.routine.database.DBHelper
  com.mad.p03.np2020.routine.database.SectionDBHelper -up-|> com.mad.p03.np2020.routine.database.DBHelper
  com.mad.p03.np2020.routine.database.TaskDBHelper -up-|> com.mad.p03.np2020.routine.database.DBHelper
  com.mad.p03.np2020.routine.database.UserDBHelper -up-|> com.mad.p03.np2020.routine.database.DBHelper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
