@startuml

title __BACKGROUND's Class Diagram__\n

  namespace com.mad.p03.np2020.routine {
    namespace background {
      class com.mad.p03.np2020.routine.background.DeleteSectionWorker {
          + DeleteSectionWorker()
          + doWork()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace background {
      class com.mad.p03.np2020.routine.background.DeleteTaskWorker {
          + DeleteTaskWorker()
          + doWork()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace background {
      class com.mad.p03.np2020.routine.background.FCMSection {
          - TAG : String
          + onMessageReceived()
          + onNewToken()
          - addSectionSQL()
          - addTaskSQL()
          - deleteSectionSQL()
          - deleteTaskSQL()
          - sendRegistrationToServer()
          - updateTask()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace background {
      class com.mad.p03.np2020.routine.background.FocusWorker {
          - mDatabase : DatabaseReference
          - result : Task<Void>
          + FocusWorker()
          + doWork()
          - deleteToFirebase()
          - deserializeFromJson()
          - writeToFirebase()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace background {
      class com.mad.p03.np2020.routine.background.GetTaskSectionWorker {
          + GetTaskSectionWorker()
          + doWork()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace background {
      class com.mad.p03.np2020.routine.background.HabitGroupWorker {
          {static} - TAG : String
          - mDatabase : DatabaseReference
          + HabitGroupWorker()
          + doWork()
          - deserializeFromJson()
          - writeToFirebase()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace background {
      class com.mad.p03.np2020.routine.background.HabitWorker {
          {static} - TAG : String
          - mDatabase : DatabaseReference
          + HabitWorker()
          + doWork()
          - deleteToFirebase()
          - deserializeFromJson()
          - writeToFirebase()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace background {
      class com.mad.p03.np2020.routine.background.RegisterFirebaseUser {
          - mActivity : Activity
          - mEmail : String
          - mPassword : String
          + RegisterFirebaseUser()
          # doInBackground()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace background {
      class com.mad.p03.np2020.routine.background.UploadDataWorker {
          + UploadDataWorker()
          + doWork()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace background {
      class com.mad.p03.np2020.routine.background.UploadSectionWorker {
          + UploadSectionWorker()
          + doWork()
      }
    }
  }
  

  namespace com.mad.p03.np2020.routine {
    namespace background {
      class com.mad.p03.np2020.routine.background.UploadTaskWorker {
          + UploadTaskWorker()
          + doWork()
      }
    }
  }
  

  com.mad.p03.np2020.routine.background.DeleteSectionWorker -up-|> androidx.work.Worker
  com.mad.p03.np2020.routine.background.DeleteTaskWorker -up-|> androidx.work.Worker
  com.mad.p03.np2020.routine.background.FCMSection -up-|> com.google.firebase.messaging.FirebaseMessagingService
  com.mad.p03.np2020.routine.background.FocusWorker -up-|> androidx.work.Worker
  com.mad.p03.np2020.routine.background.FocusWorker o-- com.mad.p03.np2020.routine.Class.Focus : focusData
  com.mad.p03.np2020.routine.background.GetTaskSectionWorker -up-|> androidx.work.Worker
  com.mad.p03.np2020.routine.background.GetTaskSectionWorker o-- com.mad.p03.np2020.routine.database.SectionDBHelper : mSectionDBHelper
  com.mad.p03.np2020.routine.background.GetTaskSectionWorker o-- com.mad.p03.np2020.routine.database.TaskDBHelper : mTaskDBHelper
  com.mad.p03.np2020.routine.background.HabitGroupWorker -up-|> androidx.work.Worker
  com.mad.p03.np2020.routine.background.HabitGroupWorker o-- com.mad.p03.np2020.routine.Class.HabitGroup : habitGroupData
  com.mad.p03.np2020.routine.background.HabitWorker -up-|> androidx.work.Worker
  com.mad.p03.np2020.routine.background.HabitWorker o-- com.mad.p03.np2020.routine.Class.Habit : habitData
  com.mad.p03.np2020.routine.background.RegisterFirebaseUser -up-|> android.os.AsyncTask
  com.mad.p03.np2020.routine.background.RegisterFirebaseUser o-- com.mad.p03.np2020.routine.Interface.OnFirebaseAuth : mOnFirebaseAuth
  com.mad.p03.np2020.routine.background.UploadDataWorker -up-|> androidx.work.Worker
  com.mad.p03.np2020.routine.background.UploadSectionWorker -up-|> androidx.work.Worker
  com.mad.p03.np2020.routine.background.UploadTaskWorker -up-|> androidx.work.Worker


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
