@startuml

title __ROUTINE's Class Diagram__\n

  namespace com.mad.p03.np2020.routine {
    class com.mad.p03.np2020.routine.BlankViewModel {
    }
  }


  namespace com.mad.p03.np2020.routine {
    class com.mad.p03.np2020.routine.Card.CardActivity {
        ~ TAG : String
        ~ noteStatus : boolean
        ~ notesFragment : Button
        ~ notifyButton : ImageButton
        ~ stepAddButton : Button
        ~ stepFragment : Button
        ~ stepStatus : boolean
        # onCreate()
    }
  }


  namespace com.mad.p03.np2020.routine {
    class com.mad.p03.np2020.routine.helpers.DividerItemDecoration {
        - space : int
        + DividerItemDecoration()
        + getItemOffsets()
    }
  }


  namespace com.mad.p03.np2020.routine {
    class com.mad.p03.np2020.routine.FocusActivity {
        ~ message : String
        ~ title : String
        - BUTTON_STATE : String
        {static} - CHANNEL_1_ID : String
        - TAG : String
        - bdownmin : boolean
        - bdownsec : boolean
        - bupmin : boolean
        - bupsec : boolean
        - currentTask : String
        - dateTimeTask : String
        - eCountDownTimer : CountDownTimer
        - focusButton : Button
        - mCompletion : String
        - mCountDownTimer : CountDownTimer
        - mTimeLeftInMillis : long
        - mface : ImageView
        - min : TextView
        - mindown : ImageView
        - minup : ImageView
        - myRef : DatabaseReference
        - repeatUpdateHandler : Handler
        - sec : TextView
        - secdown : ImageView
        - secup : ImageView
        - semicolon : TextView
        - taskInput : EditText
        - taskSubmit : ImageButton
        - textDisplay : TextView
        - tmins : int
        - tsecs : int
        + decrement()
        + increment()
        + onClick()
        + onFocusChange()
        + onFragmentInteraction()
        + onLongClick()
        + onTouch()
        + openHistory()
        + serializeToJson()
        + touchRelease()
        # onCreate()
        # onPause()
        # onResume()
        - FirebaseDatabase()
        - HideKeyboard()
        - ShowKeyboard()
        - StartTimer()
        - createNotification()
        - focusTime()
        - initialization()
        - sendChannel1()
        - timeRunner()
        - timerFail()
        - timerReset()
        - timerSuccess()
        - updateCountDownText()
        - writeDataFirebase()
        - writeToDatabase()
    }
  }


  namespace com.mad.p03.np2020.routine {
    class com.mad.p03.np2020.routine.FocusActivity.RptUpdater {
        + run()
    }
  }


  namespace com.mad.p03.np2020.routine {
    class com.mad.p03.np2020.routine.HabitActivity {
        {static} - SHARED_PREFS : String
        {static} - TAG : String
        - channelId : String
        - colorList : String[]
        - color_buttonIDS : int[]
        - color_schemeIDS : int[]
        - dateFormat : DateFormat
        - habitGroupRecyclerView : RecyclerView
        - habitRecyclerView : RecyclerView
        - hours : int
        - minutes : int
        - period_buttonIDS : int[]
        - period_countList : int[]
        - period_textList : String[]
        + cancelReminder()
        + capitalise()
        + createNotificationChannel()
        + getUniqueHabitReminderID()
        + habitGroup_serializeToJson()
        + habit_add_initialise_colorSection()
        + habit_add_initialise_periodSection()
        + habit_edit_initialise_colorSection()
        + habit_edit_initialise_periodSection()
        + habit_serializeToJson()
        + initSharedPreferences()
        + initialiseHabitNotificationChannel()
        + onClick()
        + onItemClick()
        + populateColorBtn()
        + populatePeriodBtn()
        + readHabitGroup_Firebase()
        + readHabit_Firebase()
        + setReminder()
        + writeHabitGroup_Firebase()
        + writeHabit_Firebase()
        # onCreate()
        # onStart()
        - initFirebase()
    }
  }


  namespace com.mad.p03.np2020.routine {
    class com.mad.p03.np2020.routine.HistoryFragment {
        {static} - FOCUS_DATABASE : String
        - TAG : String
        {static} - USER_GET : String
        {static} - VERTICAL_ITEM_SPACE : int
        - buttonFragment : ImageButton
        - completion : TextView
        - nothing : ImageView
        - textFragment : TextView
        + HistoryFragment()
        {static} + newInstance()
        + onAttach()
        + onCreate()
        + onCreateView()
        + onDetach()
        - initialisation()
        - sendBack()
        - updateTask()
    }
  }


  namespace com.mad.p03.np2020.routine {
    interface com.mad.p03.np2020.routine.HistoryFragment.OnFragmentInteractionListener {
        {abstract} + onFragmentInteraction()
    }
  }


  namespace com.mad.p03.np2020.routine {
    class com.mad.p03.np2020.routine.Home.Home {
        ~ TAG : String
        ~ mBackgrounds : Integer[]
        ~ mBtnAdd : Button
        ~ mBtnCancel : Button
        ~ mCardViewPopUp : CardView
        ~ mColors : Integer[]
        ~ mEditAddList : EditText
        ~ mGridView : RecyclerView
        ~ mImgAdd : FloatingActionButton
        ~ mSectionList : List<Section>
        ~ mSpinnerColor : Spinner
        ~ mSpinnerIcons : Spinner
        ~ mUID : String
        + onDataAdd()
        + onDataDelete()
        # onCreate()
        # onResume()
        # onStart()
        # onStop()
        ~ updateCard()
        - addSection()
    }
  }


  namespace com.mad.p03.np2020.routine {
    class com.mad.p03.np2020.routine.LoginActivity {
        {static} + Password : String
        {static} + SHARED_PREFS : String
        {static} + SWITCH1 : String
        {static} + Username : String
        ~ TAG : String
        ~ btn_login : Button
        ~ btn_register : Button
        ~ checkBox : CheckBox
        ~ email : String
        ~ errLogin : TextView
        ~ errPwd : TextView
        ~ et_Email : EditText
        ~ et_Password : EditText
        ~ mAuth : FirebaseAuth
        ~ password : String
        ~ txtError : TextView
        - myRef : DatabaseReference
        - sPassword : String
        - sUser : String
        - switchOnOff : boolean
        + loadData()
        + onClick()
        + onFocusChange()
        + onKey()
        + onStart()
        + saveData()
        + updateViews()
        # onCreate()
        - CheckLoggedIn()
        - HideKeyboard()
        - ShowKeyboard()
        - firebaseAuthWithGoogle()
    }
  }


  namespace com.mad.p03.np2020.routine {
    class com.mad.p03.np2020.routine.MainActivity {
        # onCreate()
    }
  }


  namespace com.mad.p03.np2020.routine {
    class com.mad.p03.np2020.routine.NotesFragment {
        + NotesFragment()
        {static} + newInstance()
        + onCreate()
        + onCreateView()
    }
  }


  namespace com.mad.p03.np2020.routine {
    class com.mad.p03.np2020.routine.Register.RegisterActivity {
        {static} ~ TAG : String
        ~ mBack : Button
        ~ mEdInput : EditText
        ~ mProgessCount : int
        ~ mSubmit : Button
        ~ mTxtErrorMessage : TextView
        ~ mTxtQuestion : TextView
        # onCreate()
        # onDestroy()
        # onPause()
        # onResume()
        # onStart()
        # onStop()
        - askDateOfBirth()
        - askEmail()
        - askName()
        - askPassword()
        - executeFirebaseUserUpload()
        - firebaseFailedError()
        - moveToHome()
        - startRegistration()
        - starterUI()
        - toggleError()
        - toggleError()
        - updateCardView()
        - updateUI()
    }
  }


  namespace com.mad.p03.np2020.routine {
    class com.mad.p03.np2020.routine.Register.RegisterActivity.RequestFirebase {
        ~ auth : FirebaseAuth
        # doInBackground()
    }
  }


  namespace com.mad.p03.np2020.routine {
    class com.mad.p03.np2020.routine.Settings {
        # onCreate()
    }
  }


  namespace com.mad.p03.np2020.routine {
    class com.mad.p03.np2020.routine.StepsFragment {
        ~ TAG : String
        ~ arrayAdapter : ArrayAdapter<String>
        ~ listView : ListView
        ~ stepAddButton : Button
        ~ stepList : List<String>
        ~ stepName : EditText
        ~ view : View
        + StepsFragment()
        + addItemToList()
        {static} + newInstance()
        + onCreate()
        + onCreateView()
    }
  }


  namespace com.mad.p03.np2020.routine {
    class com.mad.p03.np2020.routine.Task.TaskActivity {
        ~ mConstraintLayout : ConstraintLayout
        ~ mEdTask : EditText
        ~ mRecyclerView : RecyclerView
        ~ mTaskList : List<Task>
        ~ mTxtListName : TextView
        - TAG : String
        + onDataAdd()
        + onDataDelete()
        + onEditorAction()
        # onCreate()
        # onResume()
        # onStart()
        # onStop()
        - showKeyboard()
        - showNewEntry()
    }
  }


  com.mad.p03.np2020.routine.BlankViewModel -up-|> androidx.lifecycle.ViewModel
  com.mad.p03.np2020.routine.Card.CardActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.mad.p03.np2020.routine.helpers.DividerItemDecoration -up-|> androidx.recyclerview.widget.RecyclerView.ItemDecoration
  com.mad.p03.np2020.routine.FocusActivity .up.|> android.view.View.OnClickListener
  com.mad.p03.np2020.routine.FocusActivity .up.|> android.view.View.OnFocusChangeListener
  com.mad.p03.np2020.routine.FocusActivity .up.|> android.view.View.OnLongClickListener
  com.mad.p03.np2020.routine.FocusActivity .up.|> android.view.View.OnTouchListener
  com.mad.p03.np2020.routine.FocusActivity .up.|> com.mad.p03.np2020.routine.HistoryFragment.OnFragmentInteractionListener
  com.mad.p03.np2020.routine.FocusActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.mad.p03.np2020.routine.FocusActivity o-- com.mad.p03.np2020.routine.database.FocusDBHelper : focusDBHelper
  com.mad.p03.np2020.routine.FocusActivity o-- com.mad.p03.np2020.routine.Class.User : user
  com.mad.p03.np2020.routine.FocusActivity +-down- com.mad.p03.np2020.routine.FocusActivity.RptUpdater
  com.mad.p03.np2020.routine.FocusActivity.RptUpdater .up.|> java.lang.Runnable
  com.mad.p03.np2020.routine.HabitActivity .up.|> android.view.View.OnClickListener
  com.mad.p03.np2020.routine.HabitActivity .up.|> com.mad.p03.np2020.routine.helpers.OnItemClickListener
  com.mad.p03.np2020.routine.HabitActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.mad.p03.np2020.routine.HabitActivity o-- com.mad.p03.np2020.routine.Adapter.HabitGroupAdapter : groupAdapter
  com.mad.p03.np2020.routine.HabitActivity o-- com.mad.p03.np2020.routine.database.HabitGroupDBHelper : group_dbhandler
  com.mad.p03.np2020.routine.HabitActivity o-- com.mad.p03.np2020.routine.Adapter.HabitAdapter : habitAdapter
  com.mad.p03.np2020.routine.HabitActivity o-- com.mad.p03.np2020.routine.database.HabitDBHelper : habit_dbHandler
  com.mad.p03.np2020.routine.HabitActivity o-- com.mad.p03.np2020.routine.Class.User : user
  com.mad.p03.np2020.routine.HistoryFragment -up-|> androidx.fragment.app.Fragment
  com.mad.p03.np2020.routine.HistoryFragment o-- com.mad.p03.np2020.routine.database.FocusDBHelper : focusDBHelper
  com.mad.p03.np2020.routine.HistoryFragment o-- com.mad.p03.np2020.routine.HistoryFragment.OnFragmentInteractionListener : mListener
  com.mad.p03.np2020.routine.HistoryFragment o-- com.mad.p03.np2020.routine.Class.User : user
  com.mad.p03.np2020.routine.HistoryFragment +-down- com.mad.p03.np2020.routine.HistoryFragment.OnFragmentInteractionListener
  com.mad.p03.np2020.routine.Home.Home .up.|> com.mad.p03.np2020.routine.database.MyDatabaseListener
  com.mad.p03.np2020.routine.Home.Home -up-|> androidx.appcompat.app.AppCompatActivity
  com.mad.p03.np2020.routine.Home.Home o-- com.mad.p03.np2020.routine.Home.adapters.HomePageAdapter : mHomePageAdapter
  com.mad.p03.np2020.routine.Home.Home o-- com.mad.p03.np2020.routine.database.SectionDBHelper : mSectionDBHelper
  com.mad.p03.np2020.routine.Home.Home o-- com.mad.p03.np2020.routine.Class.User : mUser
  com.mad.p03.np2020.routine.LoginActivity .up.|> android.view.View.OnClickListener
  com.mad.p03.np2020.routine.LoginActivity .up.|> android.view.View.OnFocusChangeListener
  com.mad.p03.np2020.routine.LoginActivity .up.|> android.view.View.OnKeyListener
  com.mad.p03.np2020.routine.LoginActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.mad.p03.np2020.routine.LoginActivity o-- com.mad.p03.np2020.routine.database.UserDBHelper : userDatabase
  

  com.mad.p03.np2020.routine.MainActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.mad.p03.np2020.routine.NotesFragment -up-|> androidx.fragment.app.Fragment
  com.mad.p03.np2020.routine.Register.RegisterActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.mad.p03.np2020.routine.Register.RegisterActivity o-- com.mad.p03.np2020.routine.Class.User : mUser
  com.mad.p03.np2020.routine.Register.RegisterActivity +-down- com.mad.p03.np2020.routine.Register.RegisterActivity.RequestFirebase
  com.mad.p03.np2020.routine.Register.RegisterActivity.RequestFirebase -up-|> android.os.AsyncTask
  com.mad.p03.np2020.routine.Settings -up-|> androidx.appcompat.app.AppCompatActivity
  com.mad.p03.np2020.routine.StepsFragment -up-|> androidx.fragment.app.Fragment
  com.mad.p03.np2020.routine.Task.TaskActivity .up.|> android.widget.TextView.OnEditorActionListener
  com.mad.p03.np2020.routine.Task.TaskActivity .up.|> com.mad.p03.np2020.routine.database.MyDatabaseListener
  com.mad.p03.np2020.routine.Task.TaskActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.mad.p03.np2020.routine.Task.TaskActivity o-- com.mad.p03.np2020.routine.Class.Section : mSection
  com.mad.p03.np2020.routine.Task.TaskActivity o-- com.mad.p03.np2020.routine.Task.adapter.TaskAdapter : mTaskAdapter

@enduml
