@startuml

title __BlankViewModel's Class Diagram__\n

    namespace com.mad.p03.np2020.routine {
        class com.mad.p03.np2020.routine.CardActivity {
            ~ TAG : String
            ~ cardName : EditText
            ~ noteStatus : boolean
            ~ notesFragment : Button
            ~ notifyButton : ImageButton
            ~ stepAddButton : Button
            ~ stepFragment : Button
            ~ stepStatus : boolean
            # onCreate()
            # onStop()
            - showNewEntry()
        }
      }

    com.mad.p03.np2020.routine.CardActivity -up-|> androidx.appcompat.app.AppCompatActivity
      com.mad.p03.np2020.routine.CardActivity o-- com.mad.p03.np2020.routine.Class.Task : mTask
      com.mad.p03.np2020.routine.CardActivity o-- com.mad.p03.np2020.routine.database.TaskDBHelper : mTaskDBHelper
@enduml
